spring:
  application:
    name: trello-api

  data:
    mongodb:
      uri: mongodb+srv://coladz2812:jJdl6I8vBAQyOrN9@cola.parrxmg.mongodb.net/trello-coladeptrai?retryWrites=true&w=majority&appName=CoLa

server:
  port: 8017

app:
  cors:
    whitelist: https://trello-web-plum.vercel.app , http://localhost:3000