spring:
  application:
    name: trello-api

  data:
    mongodb:
      uri: ${MONGO_URI}  # đọc từ biến môi trường

mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USER}
    password: ${GMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


server:
  port: 8017

app:
  cors:
    whitelist: https://trello-web-plum.vercel.app, http://localhost:3000

brevo:
  api:
    key: ${BREVO_API_KEY}
  email:
    name: ${BREVO_EMAIL}
    senderName: Trello Advance MERN Stack

jwt :
  signerKey : ${SIGNER_KEY}
  valid-duration : 200 # in second thơig gian có hiệu lực cùa token
  refreshable-duration : 360 #in second thời gian có thể làm mới token
